### PR TITLE
DSTBACK-2335 Update F13 docs based on script

### PR DESCRIPTION
**Pull request by joegrimeringresso**
I started a script here:

https://github.com/ingresso-group/dirty-horrible-scripts/commit/a3bf21769692500d5b06efef3ce4038219ff9cd0

Using it to find missing things in the docs

### CODE REVIEW

**Comment by joegrimeringresso** [comment]
@ingresso-pete Should we add `exclude_dead_events` to events.v1 docs?

**Comment by ingresso-pete** [comment]
My opinion is to document the `s_` variants, and put an extra section saying "some of these have ;friendly'; aliases. These used to be recommended, and are preserved for backwards compatibility".

I prefer people to use the s_ ones. The friendly ones were always an arbitrary mess. Adding one for times just makes more arbitrary mess.

**Comment by joegrimeringresso** [comment]
not adding `exclude_dead_events` because there's already `include_dead`

**Comment by joegrimeringresso** [comment]
not adding `exclude_dead_events` because there's already `include_dead`

**Pull request merged**
